

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class Email : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Email entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Email()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Email(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Email> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Email.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Email_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Email_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Email.DetailsClass.GetValue(this, global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Email.DetailsClass.SetValue(this, global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Email.DetailsClass.GetValue(this, global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Email.DetailsClass.SetValue(this, global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string RolMail
        {
            get
            {
                return global::LightSwitchApplication.Email.DetailsClass.GetValue(this, global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties.RolMail);
            }
            set
            {
                global::LightSwitchApplication.Email.DetailsClass.SetValue(this, global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties.RolMail, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RolMail_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RolMail_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RolMail_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Destinatario
        {
            get
            {
                return global::LightSwitchApplication.Email.DetailsClass.GetValue(this, global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties.Destinatario);
            }
            set
            {
                global::LightSwitchApplication.Email.DetailsClass.SetValue(this, global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties.Destinatario, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Destinatario_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Destinatario_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Destinatario_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Mail
        {
            get
            {
                return global::LightSwitchApplication.Email.DetailsClass.GetValue(this, global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties.Mail);
            }
            set
            {
                global::LightSwitchApplication.Email.DetailsClass.SetValue(this, global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties.Mail, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Mail_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Mail_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Mail_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string DestinatarioMail
        {
            get
            {
                return global::LightSwitchApplication.Email.DetailsClass.GetValue(this, global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties.DestinatarioMail);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DestinatarioMail_Compute(ref string result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DestinatarioMail_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Email,
                global::LightSwitchApplication.Email.DetailsClass,
                global::LightSwitchApplication.Email.DetailsClass.IImplementation,
                global::LightSwitchApplication.Email.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass>.Entry
                __EmailEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass>.Entry(
                    global::LightSwitchApplication.Email.DetailsClass.__Email_CreateNew,
                    global::LightSwitchApplication.Email.DetailsClass.__Email_Created,
                    global::LightSwitchApplication.Email.DetailsClass.__Email_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Email __Email_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Email> es)
            {
                return new global::LightSwitchApplication.Email(es);
            }
            private static void __Email_Created(global::LightSwitchApplication.Email e)
            {
                e.Email_Created();
            }
            private static bool __Email_AllowSaveWithErrors(global::LightSwitchApplication.Email e)
            {
                bool result = false;
                e.Email_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Email.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, string> RolMail
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties.RolMail) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, string> Destinatario
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties.Destinatario) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, string> Mail
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties.Mail) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, string> DestinatarioMail
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties.DestinatarioMail) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new string RolMail { get; set; }
                new string Destinatario { get; set; }
                new string Mail { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Email.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, int>.Data> c, global::LightSwitchApplication.Email.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Email e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Email e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Email.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Email.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Email e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Email.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Email.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Email e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Email e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Email.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Email.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Email e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, string>.Entry
                    RolMail = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, string>.Entry(
                        "RolMail",
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._RolMail_Stub,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._RolMail_ComputeIsReadOnly,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._RolMail_Validate,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._RolMail_GetImplementationValue,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._RolMail_SetImplementationValue,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._RolMail_OnValueChanged);
                private static void _RolMail_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Email.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, string>.Data> c, global::LightSwitchApplication.Email.DetailsClass d, object sf)
                {
                    c(d, ref d._RolMail, sf);
                }
                private static bool _RolMail_ComputeIsReadOnly(global::LightSwitchApplication.Email e)
                {
                    bool result = false;
                    e.RolMail_IsReadOnly(ref result);
                    return result;
                }
                private static void _RolMail_Validate(global::LightSwitchApplication.Email e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RolMail_Validate(r);
                }
                private static string _RolMail_GetImplementationValue(global::LightSwitchApplication.Email.DetailsClass d)
                {
                    return d.ImplementationEntity.RolMail;
                }
                private static void _RolMail_SetImplementationValue(global::LightSwitchApplication.Email.DetailsClass d, string v)
                {
                    d.ImplementationEntity.RolMail = v;
                }
                private static void _RolMail_OnValueChanged(global::LightSwitchApplication.Email e)
                {
                    e.RolMail_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, string>.Entry
                    Destinatario = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, string>.Entry(
                        "Destinatario",
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._Destinatario_Stub,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._Destinatario_ComputeIsReadOnly,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._Destinatario_Validate,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._Destinatario_GetImplementationValue,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._Destinatario_SetImplementationValue,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._Destinatario_OnValueChanged);
                private static void _Destinatario_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Email.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, string>.Data> c, global::LightSwitchApplication.Email.DetailsClass d, object sf)
                {
                    c(d, ref d._Destinatario, sf);
                }
                private static bool _Destinatario_ComputeIsReadOnly(global::LightSwitchApplication.Email e)
                {
                    bool result = false;
                    e.Destinatario_IsReadOnly(ref result);
                    return result;
                }
                private static void _Destinatario_Validate(global::LightSwitchApplication.Email e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Destinatario_Validate(r);
                }
                private static string _Destinatario_GetImplementationValue(global::LightSwitchApplication.Email.DetailsClass d)
                {
                    return d.ImplementationEntity.Destinatario;
                }
                private static void _Destinatario_SetImplementationValue(global::LightSwitchApplication.Email.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Destinatario = v;
                }
                private static void _Destinatario_OnValueChanged(global::LightSwitchApplication.Email e)
                {
                    e.Destinatario_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, string>.Entry
                    Mail = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, string>.Entry(
                        "Mail",
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._Mail_Stub,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._Mail_ComputeIsReadOnly,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._Mail_Validate,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._Mail_GetImplementationValue,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._Mail_SetImplementationValue,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._Mail_OnValueChanged);
                private static void _Mail_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Email.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, string>.Data> c, global::LightSwitchApplication.Email.DetailsClass d, object sf)
                {
                    c(d, ref d._Mail, sf);
                }
                private static bool _Mail_ComputeIsReadOnly(global::LightSwitchApplication.Email e)
                {
                    bool result = false;
                    e.Mail_IsReadOnly(ref result);
                    return result;
                }
                private static void _Mail_Validate(global::LightSwitchApplication.Email e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Mail_Validate(r);
                }
                private static string _Mail_GetImplementationValue(global::LightSwitchApplication.Email.DetailsClass d)
                {
                    return d.ImplementationEntity.Mail;
                }
                private static void _Mail_SetImplementationValue(global::LightSwitchApplication.Email.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Mail = v;
                }
                private static void _Mail_OnValueChanged(global::LightSwitchApplication.Email e)
                {
                    e.Mail_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, string>.Entry
                    DestinatarioMail = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, string>.Entry(
                        "DestinatarioMail",
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._DestinatarioMail_Stub,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._DestinatarioMail_Validate,
                        global::LightSwitchApplication.Email.DetailsClass.PropertySetProperties._DestinatarioMail_ComputeValue);
                private static void _DestinatarioMail_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Email.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, string>.Data> c, global::LightSwitchApplication.Email.DetailsClass d, object sf)
                {
                    c(d, ref d._DestinatarioMail, sf);
                }
                private static void _DestinatarioMail_Validate(global::LightSwitchApplication.Email e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DestinatarioMail_Validate(r);
                }
                private static string _DestinatarioMail_ComputeValue(global::LightSwitchApplication.Email e)
                {
                    string value = default(string);
                    e.DestinatarioMail_Compute(ref value);
                    return value;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, string>.Data _RolMail;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, string>.Data _Destinatario;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, string>.Data _Mail;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Email, global::LightSwitchApplication.Email.DetailsClass, string>.Data _DestinatarioMail;
            
        }
    
        #endregion
    }
    
    #endregion
}
