//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region Cheque
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Cheque :
        global::LightSwitchApplication.Cheque.DetailsClass.IImplementation
    {
        partial void OnCheque_CuentaBancoChanged()
        {
            this.___OnPropertyChanged("Cheque_CuentaBanco");
            this.___OnPropertyChanged("CuentaBanco");
        }
        
        partial void OnCheque_BeneficiarioChanged()
        {
            this.___OnPropertyChanged("Cheque_Beneficiario");
            this.___OnPropertyChanged("Beneficiario");
        }
        
        partial void OnCheque_CobradorChanged()
        {
            this.___OnPropertyChanged("Cheque_Cobrador");
            this.___OnPropertyChanged("Cobrador");
        }
        
        partial void OnCheque_GiradorChanged()
        {
            this.___OnPropertyChanged("Cheque_Girador");
            this.___OnPropertyChanged("Girador");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnNroChanged()
        {
            this.___OnPropertyChanged("Nro");
        }
        
        partial void OnConceptoChanged()
        {
            this.___OnPropertyChanged("Concepto");
        }
        
        partial void OnMontoChanged()
        {
            this.___OnPropertyChanged("Monto");
        }
        
        partial void OnFechaGiroChanged()
        {
            this.___OnPropertyChanged("FechaGiro");
        }
        
        partial void OnCertificadoChanged()
        {
            this.___OnPropertyChanged("Certificado");
        }
        
        partial void OnComprobanteNroChanged()
        {
            this.___OnPropertyChanged("ComprobanteNro");
        }
        
        partial void OnImgChequeChanged()
        {
            this.___OnPropertyChanged("ImgCheque");
        }
        
        partial void OnImgFacturaChanged()
        {
            this.___OnPropertyChanged("ImgFactura");
        }
        
        partial void OnImgComprobanteChanged()
        {
            this.___OnPropertyChanged("ImgComprobante");
        }
        
        partial void OnImgDocRespaldoChanged()
        {
            this.___OnPropertyChanged("ImgDocRespaldo");
        }
        
        partial void OnSituacionChanged()
        {
            this.___OnPropertyChanged("Situacion");
        }
        
        partial void OnSolicitarChanged()
        {
            this.___OnPropertyChanged("Solicitar");
        }
        
        partial void OnSolicitudNroChanged()
        {
            this.___OnPropertyChanged("SolicitudNro");
        }
        
        partial void OnObservacionChanged()
        {
            this.___OnPropertyChanged("Observacion");
        }
        
        partial void OnUsuarioCreacionChanged()
        {
            this.___OnPropertyChanged("UsuarioCreacion");
        }
        
        partial void OnFechaCreacionChanged()
        {
            this.___OnPropertyChanged("FechaCreacion");
        }
        
        partial void OnUsuarioAprobacionChanged()
        {
            this.___OnPropertyChanged("UsuarioAprobacion");
        }
        
        partial void OnFechaAprobaciónChanged()
        {
            this.___OnPropertyChanged("FechaAprobación");
        }
        
        partial void OnUsuarioSolicitudChanged()
        {
            this.___OnPropertyChanged("UsuarioSolicitud");
        }
        
        partial void OnFechaSolicitudChanged()
        {
            this.___OnPropertyChanged("FechaSolicitud");
        }
        
        partial void OnUsuarioEmisionChanged()
        {
            this.___OnPropertyChanged("UsuarioEmision");
        }
        
        partial void OnFechaEmisionChanged()
        {
            this.___OnPropertyChanged("FechaEmision");
        }
        
        partial void OnUsuarioPagoChanged()
        {
            this.___OnPropertyChanged("UsuarioPago");
        }
        
        partial void OnFechaPagoChanged()
        {
            this.___OnPropertyChanged("FechaPago");
        }
        
        partial void OnUsuarioAnulacionChanged()
        {
            this.___OnPropertyChanged("UsuarioAnulacion");
        }
        
        partial void OnFechaAnulaciónChanged()
        {
            this.___OnPropertyChanged("FechaAnulación");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Cheque.DetailsClass.IImplementation.CuentaBanco
        {
            get
            {
                return this.CuentaBanco;
            }
            set
            {
                this.CuentaBanco = (global::LightSwitchApplication.Implementation.CuentaBanco)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.CuentaBanco> __CuentaBanco
        {
            get
            {
                if (this.___CuentaBanco == null)
                {
                    this.___CuentaBanco = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.CuentaBanco>(
                        this,
                        "CuentaBanco",
                        new string[] { "Cheque_CuentaBanco" },
                        e => global::System.Object.Equals(e.Id, this.Cheque_CuentaBanco),
                        () => this._CuentaBanco,
                        e => this._CuentaBanco = e);
                }
                return this.___CuentaBanco;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.CuentaBanco> ___CuentaBanco;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Cheque.DetailsClass.IImplementation.Beneficiario
        {
            get
            {
                return this.Beneficiario;
            }
            set
            {
                this.Beneficiario = (global::LightSwitchApplication.Implementation.Beneficiario)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Beneficiario> __Beneficiario
        {
            get
            {
                if (this.___Beneficiario == null)
                {
                    this.___Beneficiario = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Beneficiario>(
                        this,
                        "Beneficiario",
                        new string[] { "Cheque_Beneficiario" },
                        e => global::System.Object.Equals(e.Id, this.Cheque_Beneficiario),
                        () => this._Beneficiario,
                        e => this._Beneficiario = e);
                }
                return this.___Beneficiario;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Beneficiario> ___Beneficiario;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Cheque.DetailsClass.IImplementation.Cobrador
        {
            get
            {
                return this.Cobrador;
            }
            set
            {
                this.Cobrador = (global::LightSwitchApplication.Implementation.Cobrador)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Cobrador> __Cobrador
        {
            get
            {
                if (this.___Cobrador == null)
                {
                    this.___Cobrador = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Cobrador>(
                        this,
                        "Cobrador",
                        new string[] { "Cheque_Cobrador" },
                        e => global::System.Object.Equals(e.Id, this.Cheque_Cobrador),
                        () => this._Cobrador,
                        e => this._Cobrador = e);
                }
                return this.___Cobrador;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Cobrador> ___Cobrador;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Cheque.DetailsClass.IImplementation.Girador
        {
            get
            {
                return this.Girador;
            }
            set
            {
                this.Girador = (global::LightSwitchApplication.Implementation.Girador)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Girador> __Girador
        {
            get
            {
                if (this.___Girador == null)
                {
                    this.___Girador = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Girador>(
                        this,
                        "Girador",
                        new string[] { "Cheque_Girador" },
                        e => global::System.Object.Equals(e.Id, this.Cheque_Girador),
                        () => this._Girador,
                        e => this._Girador = e);
                }
                return this.___Girador;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Girador> ___Girador;
        
    }
    #endregion
    
    #region CuentaBanco
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class CuentaBanco :
        global::LightSwitchApplication.CuentaBanco.DetailsClass.IImplementation
    {
        partial void OnCuentaBanco_BancoChanged()
        {
            this.___OnPropertyChanged("CuentaBanco_Banco");
            this.___OnPropertyChanged("Banco");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnCuentaNroChanged()
        {
            this.___OnPropertyChanged("CuentaNro");
        }
        
        partial void OnMonedaChanged()
        {
            this.___OnPropertyChanged("Moneda");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.CuentaBanco.DetailsClass.IImplementation.Banco
        {
            get
            {
                return this.Banco;
            }
            set
            {
                this.Banco = (global::LightSwitchApplication.Implementation.Banco)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Banco> __Banco
        {
            get
            {
                if (this.___Banco == null)
                {
                    this.___Banco = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Banco>(
                        this,
                        "Banco",
                        new string[] { "CuentaBanco_Banco" },
                        e => global::System.Object.Equals(e.Id, this.CuentaBanco_Banco),
                        () => this._Banco,
                        e => this._Banco = e);
                }
                return this.___Banco;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Banco> ___Banco;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.CuentaBanco.DetailsClass.IImplementation.Cheques
        {
            get
            {
                return this.Cheques;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Cheque> __Cheques
        {
            get
            {
                if (this.___Cheques == null)
                {
                    this.___Cheques = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Cheque>(
                        this,
                        "Cheques",
                        () => this._Cheques,
                        e => global::System.Object.Equals(e.Cheque_CuentaBanco, this.Id));
                }
                return this.___Cheques;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Cheque> ___Cheques;
        
    }
    #endregion
    
    #region Beneficiario
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Beneficiario :
        global::LightSwitchApplication.Beneficiario.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnNombreChanged()
        {
            this.___OnPropertyChanged("Nombre");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Beneficiario.DetailsClass.IImplementation.Cheques
        {
            get
            {
                return this.Cheques;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Cheque> __Cheques
        {
            get
            {
                if (this.___Cheques == null)
                {
                    this.___Cheques = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Cheque>(
                        this,
                        "Cheques",
                        () => this._Cheques,
                        e => global::System.Object.Equals(e.Cheque_Beneficiario, this.Id));
                }
                return this.___Cheques;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Cheque> ___Cheques;
        
    }
    #endregion
    
    #region Cobrador
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Cobrador :
        global::LightSwitchApplication.Cobrador.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnNombreChanged()
        {
            this.___OnPropertyChanged("Nombre");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Cobrador.DetailsClass.IImplementation.Cheques
        {
            get
            {
                return this.Cheques;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Cheque> __Cheques
        {
            get
            {
                if (this.___Cheques == null)
                {
                    this.___Cheques = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Cheque>(
                        this,
                        "Cheques",
                        () => this._Cheques,
                        e => global::System.Object.Equals(e.Cheque_Cobrador, this.Id));
                }
                return this.___Cheques;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Cheque> ___Cheques;
        
    }
    #endregion
    
    #region Email
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Email :
        global::LightSwitchApplication.Email.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnRolMailChanged()
        {
            this.___OnPropertyChanged("RolMail");
        }
        
        partial void OnDestinatarioChanged()
        {
            this.___OnPropertyChanged("Destinatario");
        }
        
        partial void OnMailChanged()
        {
            this.___OnPropertyChanged("Mail");
        }
        
    }
    #endregion
    
    #region Banco
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Banco :
        global::LightSwitchApplication.Banco.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnSiglaChanged()
        {
            this.___OnPropertyChanged("Sigla");
        }
        
        partial void OnNombreChanged()
        {
            this.___OnPropertyChanged("Nombre");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Banco.DetailsClass.IImplementation.CuentaBancos
        {
            get
            {
                return this.CuentaBancos;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CuentaBanco> __CuentaBancos
        {
            get
            {
                if (this.___CuentaBancos == null)
                {
                    this.___CuentaBancos = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CuentaBanco>(
                        this,
                        "CuentaBancos",
                        () => this._CuentaBancos,
                        e => global::System.Object.Equals(e.CuentaBanco_Banco, this.Id));
                }
                return this.___CuentaBancos;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.CuentaBanco> ___CuentaBancos;
        
    }
    #endregion
    
    #region Girador
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Girador :
        global::LightSwitchApplication.Girador.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnNombreChanged()
        {
            this.___OnPropertyChanged("Nombre");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Girador.DetailsClass.IImplementation.Cheques
        {
            get
            {
                return this.Cheques;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Cheque> __Cheques
        {
            get
            {
                if (this.___Cheques == null)
                {
                    this.___Cheques = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Cheque>(
                        this,
                        "Cheques",
                        () => this._Cheques,
                        e => global::System.Object.Equals(e.Cheque_Girador, this.Id));
                }
                return this.___Cheques;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Cheque> ___Cheques;
        
    }
    #endregion
    
    #region SendMail
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class SendMail :
        global::LightSwitchApplication.SendMail.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnFechaChanged()
        {
            this.___OnPropertyChanged("Fecha");
        }
        
        partial void OnRolMailChanged()
        {
            this.___OnPropertyChanged("RolMail");
        }
        
        partial void OnMailToChanged()
        {
            this.___OnPropertyChanged("MailTo");
        }
        
        partial void OnMailFromChanged()
        {
            this.___OnPropertyChanged("MailFrom");
        }
        
        partial void OnSubjectChanged()
        {
            this.___OnPropertyChanged("Subject");
        }
        
        partial void OnBodyChanged()
        {
            this.___OnPropertyChanged("Body");
        }
        
        partial void OnCodigoChanged()
        {
            this.___OnPropertyChanged("Codigo");
        }
        
    }
    #endregion
    
    #region Secuencia
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Secuencia :
        global::LightSwitchApplication.Secuencia.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnCatagoriaChanged()
        {
            this.___OnPropertyChanged("Catagoria");
        }
        
        partial void OnClaveChanged()
        {
            this.___OnPropertyChanged("Clave");
        }
        
        partial void OnNroActualChanged()
        {
            this.___OnPropertyChanged("NroActual");
        }
        
        partial void OnNroInicialChanged()
        {
            this.___OnPropertyChanged("NroInicial");
        }
        
        partial void OnNroFinalChanged()
        {
            this.___OnPropertyChanged("NroFinal");
        }
        
    }
    #endregion
    
    #region Log
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Log :
        global::LightSwitchApplication.Log.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnFechaChanged()
        {
            this.___OnPropertyChanged("Fecha");
        }
        
        partial void OnUsuarioChanged()
        {
            this.___OnPropertyChanged("Usuario");
        }
        
        partial void OnObjetoChanged()
        {
            this.___OnPropertyChanged("Objeto");
        }
        
        partial void OnMetodoChanged()
        {
            this.___OnPropertyChanged("Metodo");
        }
        
        partial void OnDetalleChanged()
        {
            this.___OnPropertyChanged("Detalle");
        }
        
    }
    #endregion
    
    #region OperacionEMail
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class OperacionEMail :
        global::LightSwitchApplication.OperacionEMail.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnEnvianteChanged()
        {
            this.___OnPropertyChanged("Enviante");
        }
        
        partial void OnDestinatarioChanged()
        {
            this.___OnPropertyChanged("Destinatario");
        }
        
        partial void OnAsuntoChanged()
        {
            this.___OnPropertyChanged("Asunto");
        }
        
        partial void OnCuerpoChanged()
        {
            this.___OnPropertyChanged("Cuerpo");
        }
        
        partial void OnInfoAdjuntaChanged()
        {
            this.___OnPropertyChanged("InfoAdjunta");
        }
        
        partial void OnNombreArchivoAdjuntoChanged()
        {
            this.___OnPropertyChanged("NombreArchivoAdjunto");
        }
        
    }
    #endregion
    
    #region Parametro
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Parametro :
        global::LightSwitchApplication.Parametro.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnCategoriaChanged()
        {
            this.___OnPropertyChanged("Categoria");
        }
        
        partial void OnClaveChanged()
        {
            this.___OnPropertyChanged("Clave");
        }
        
        partial void OnValorChanged()
        {
            this.___OnPropertyChanged("Valor");
        }
        
    }
    #endregion
    
    #region ApplicationDataObjectContext
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ApplicationDataObjectContext
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Cheque))
            {
                return new global::LightSwitchApplication.Implementation.Cheque();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.CuentaBanco))
            {
                return new global::LightSwitchApplication.Implementation.CuentaBanco();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Beneficiario))
            {
                return new global::LightSwitchApplication.Implementation.Beneficiario();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Cobrador))
            {
                return new global::LightSwitchApplication.Implementation.Cobrador();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Email))
            {
                return new global::LightSwitchApplication.Implementation.Email();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Banco))
            {
                return new global::LightSwitchApplication.Implementation.Banco();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Girador))
            {
                return new global::LightSwitchApplication.Implementation.Girador();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.SendMail))
            {
                return new global::LightSwitchApplication.Implementation.SendMail();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Secuencia))
            {
                return new global::LightSwitchApplication.Implementation.Secuencia();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Log))
            {
                return new global::LightSwitchApplication.Implementation.Log();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.OperacionEMail))
            {
                return new global::LightSwitchApplication.Implementation.OperacionEMail();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Parametro))
            {
                return new global::LightSwitchApplication.Implementation.Parametro();
            }
            return null;
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationDataObjectContext(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../ApplicationData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Cheque) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Cheque);
            }
            if (typeof(global::LightSwitchApplication.CuentaBanco) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.CuentaBanco);
            }
            if (typeof(global::LightSwitchApplication.Beneficiario) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Beneficiario);
            }
            if (typeof(global::LightSwitchApplication.Cobrador) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Cobrador);
            }
            if (typeof(global::LightSwitchApplication.Email) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Email);
            }
            if (typeof(global::LightSwitchApplication.Banco) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Banco);
            }
            if (typeof(global::LightSwitchApplication.Girador) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Girador);
            }
            if (typeof(global::LightSwitchApplication.SendMail) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.SendMail);
            }
            if (typeof(global::LightSwitchApplication.Secuencia) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Secuencia);
            }
            if (typeof(global::LightSwitchApplication.Log) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Log);
            }
            if (typeof(global::LightSwitchApplication.OperacionEMail) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.OperacionEMail);
            }
            if (typeof(global::LightSwitchApplication.Parametro) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Parametro);
            }
            return null;
        }
    }
}
