//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System.Linq;

namespace LightSwitchApplication.Implementation
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::ApplicationData.Implementation.ApplicationDataObjectContext>
    {
    
        public ApplicationDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService()
        {
            return new global::LightSwitchApplication.DataWorkspace().ApplicationData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::ApplicationData.Implementation.ApplicationDataObjectContext>
    {
        public ApplicationDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
        public global::System.Linq.IQueryable<global::ApplicationData.Implementation.Cheque> ChequesPorCuentaBanco(global::System.Nullable<int> CuentaId)
        {
            global::System.Linq.IQueryable<global::ApplicationData.Implementation.Cheque> query;
            query = global::System.Linq.Queryable.OrderBy(
                global::System.Linq.Queryable.Where(
                    this.GetQuery<global::ApplicationData.Implementation.Cheque>("Cheques"),
                    (c) => (CuentaId.HasValue && (c.CuentaBanco.Id == CuentaId))),
                (c) => c.Nro);
            return query;
        }
    
        public global::System.Linq.IQueryable<global::ApplicationData.Implementation.Cheque> ChequesPorCuentaBancoYSituacion(global::System.Nullable<int> CuentaId, string Situacion)
        {
            global::System.Linq.IQueryable<global::ApplicationData.Implementation.Cheque> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::ApplicationData.Implementation.Cheque>("ChequesPorCuentaBanco", CuentaId),
                (c) => (c.Situacion.CompareTo(Situacion) == 0));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::ApplicationData.Implementation.CuentaBanco> CuentaBancosOrdenada()
        {
            global::System.Linq.IQueryable<global::ApplicationData.Implementation.CuentaBanco> query;
            query = global::System.Linq.Queryable.ThenBy(
                global::System.Linq.Queryable.ThenBy(
                    global::System.Linq.Queryable.OrderBy(
                        this.GetQuery<global::ApplicationData.Implementation.CuentaBanco>("CuentaBancos"),
                        (c) => c.Banco.Sigla),
                    (c) => c.Moneda),
                (c) => c.CuentaNro);
            return query;
        }
    
        public global::System.Linq.IQueryable<global::ApplicationData.Implementation.Beneficiario> BeneficiariosOrdenados()
        {
            global::System.Linq.IQueryable<global::ApplicationData.Implementation.Beneficiario> query;
            query = global::System.Linq.Queryable.OrderBy(
                this.GetQuery<global::ApplicationData.Implementation.Beneficiario>("Beneficiarios"),
                (b) => b.Nombre);
            return query;
        }
    
        public global::System.Linq.IQueryable<global::ApplicationData.Implementation.Cobrador> CobradoresOrdenados()
        {
            global::System.Linq.IQueryable<global::ApplicationData.Implementation.Cobrador> query;
            query = global::System.Linq.Queryable.OrderBy(
                this.GetQuery<global::ApplicationData.Implementation.Cobrador>("Cobradors"),
                (c) => c.Nombre);
            return query;
        }
    
        public global::System.Linq.IQueryable<global::ApplicationData.Implementation.Girador> GiradoresOrdenados()
        {
            global::System.Linq.IQueryable<global::ApplicationData.Implementation.Girador> query;
            query = global::System.Linq.Queryable.OrderBy(
                this.GetQuery<global::ApplicationData.Implementation.Girador>("Giradors"),
                (g) => g.Nombre);
            return query;
        }
    
        public global::System.Linq.IQueryable<global::ApplicationData.Implementation.Email> EmailsOrdenados()
        {
            global::System.Linq.IQueryable<global::ApplicationData.Implementation.Email> query;
            query = global::System.Linq.Queryable.ThenBy(
                global::System.Linq.Queryable.OrderBy(
                    this.GetQuery<global::ApplicationData.Implementation.Email>("Emails"),
                    (e) => e.RolMail),
                (e) => e.Destinatario);
            return query;
        }
    
        public global::System.Linq.IQueryable<global::ApplicationData.Implementation.Banco> BancosOrdenados()
        {
            global::System.Linq.IQueryable<global::ApplicationData.Implementation.Banco> query;
            query = global::System.Linq.Queryable.OrderBy(
                this.GetQuery<global::ApplicationData.Implementation.Banco>("Bancos"),
                (b) => b.Sigla);
            return query;
        }
    
        public global::System.Linq.IQueryable<global::ApplicationData.Implementation.Secuencia> SecuenciasOrdenadas()
        {
            global::System.Linq.IQueryable<global::ApplicationData.Implementation.Secuencia> query;
            query = global::System.Linq.Queryable.ThenBy(
                global::System.Linq.Queryable.OrderBy(
                    this.GetQuery<global::ApplicationData.Implementation.Secuencia>("Secuencias"),
                    (s) => s.Catagoria),
                (s) => s.Clave);
            return query;
        }
    
        public global::System.Linq.IQueryable<global::ApplicationData.Implementation.Parametro> ParametrosOrdenados()
        {
            global::System.Linq.IQueryable<global::ApplicationData.Implementation.Parametro> query;
            query = global::System.Linq.Queryable.ThenBy(
                global::System.Linq.Queryable.OrderBy(
                    this.GetQuery<global::ApplicationData.Implementation.Parametro>("Parametros"),
                    (p) => p.Categoria),
                (p) => p.Clave);
            return query;
        }
    
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::ApplicationData.Implementation.Cheque))
            {
                return new global::ApplicationData.Implementation.Cheque();
            }
            if (type == typeof(global::ApplicationData.Implementation.CuentaBanco))
            {
                return new global::ApplicationData.Implementation.CuentaBanco();
            }
            if (type == typeof(global::ApplicationData.Implementation.Beneficiario))
            {
                return new global::ApplicationData.Implementation.Beneficiario();
            }
            if (type == typeof(global::ApplicationData.Implementation.Cobrador))
            {
                return new global::ApplicationData.Implementation.Cobrador();
            }
            if (type == typeof(global::ApplicationData.Implementation.Email))
            {
                return new global::ApplicationData.Implementation.Email();
            }
            if (type == typeof(global::ApplicationData.Implementation.Banco))
            {
                return new global::ApplicationData.Implementation.Banco();
            }
            if (type == typeof(global::ApplicationData.Implementation.Girador))
            {
                return new global::ApplicationData.Implementation.Girador();
            }
            if (type == typeof(global::ApplicationData.Implementation.SendMail))
            {
                return new global::ApplicationData.Implementation.SendMail();
            }
            if (type == typeof(global::ApplicationData.Implementation.Secuencia))
            {
                return new global::ApplicationData.Implementation.Secuencia();
            }
            if (type == typeof(global::ApplicationData.Implementation.Log))
            {
                return new global::ApplicationData.Implementation.Log();
            }
            if (type == typeof(global::ApplicationData.Implementation.OperacionEMail))
            {
                return new global::ApplicationData.Implementation.OperacionEMail();
            }
            if (type == typeof(global::ApplicationData.Implementation.Parametro))
            {
                return new global::ApplicationData.Implementation.Parametro();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::ApplicationData.Implementation.ApplicationDataObjectContext CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::ApplicationData.Implementation.ApplicationDataObjectContext(base.GetEntityConnectionString(
                "_IntrinsicData", 
                "res://" + assemblyName + "/ApplicationData.csdl|res://" + assemblyName + "/ApplicationData.ssdl|res://" + assemblyName + "/ApplicationData.msl", 
                "System.Data.SqlClient"));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Cheque))
            {
                return new global::ApplicationData.Implementation.Cheque();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.CuentaBanco))
            {
                return new global::ApplicationData.Implementation.CuentaBanco();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Beneficiario))
            {
                return new global::ApplicationData.Implementation.Beneficiario();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Cobrador))
            {
                return new global::ApplicationData.Implementation.Cobrador();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Email))
            {
                return new global::ApplicationData.Implementation.Email();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Banco))
            {
                return new global::ApplicationData.Implementation.Banco();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Girador))
            {
                return new global::ApplicationData.Implementation.Girador();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.SendMail))
            {
                return new global::ApplicationData.Implementation.SendMail();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Secuencia))
            {
                return new global::ApplicationData.Implementation.Secuencia();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Log))
            {
                return new global::ApplicationData.Implementation.Log();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.OperacionEMail))
            {
                return new global::ApplicationData.Implementation.OperacionEMail();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Parametro))
            {
                return new global::ApplicationData.Implementation.Parametro();
            }
            return null;
        }
    
    #endregion
    
    }
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class DataServiceFactory :
        global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationDataService();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationDataServiceImplementation(dataService);
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Cheque) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.Cheque);
            }
            if (typeof(global::LightSwitchApplication.CuentaBanco) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.CuentaBanco);
            }
            if (typeof(global::LightSwitchApplication.Beneficiario) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.Beneficiario);
            }
            if (typeof(global::LightSwitchApplication.Cobrador) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.Cobrador);
            }
            if (typeof(global::LightSwitchApplication.Email) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.Email);
            }
            if (typeof(global::LightSwitchApplication.Banco) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.Banco);
            }
            if (typeof(global::LightSwitchApplication.Girador) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.Girador);
            }
            if (typeof(global::LightSwitchApplication.SendMail) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.SendMail);
            }
            if (typeof(global::LightSwitchApplication.Secuencia) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.Secuencia);
            }
            if (typeof(global::LightSwitchApplication.Log) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.Log);
            }
            if (typeof(global::LightSwitchApplication.OperacionEMail) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.OperacionEMail);
            }
            if (typeof(global::LightSwitchApplication.Parametro) == definitionType)
            {
                return typeof(global::ApplicationData.Implementation.Parametro);
            }
            return null;
        }
    }
}

namespace ApplicationData.Implementation
{

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Cheque :
        global::LightSwitchApplication.Cheque.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Cheque.DetailsClass.IImplementation.CuentaBanco
        {
            get
            {
                return this.CuentaBanco;
            }
            set
            {
                this.CuentaBanco = (global::ApplicationData.Implementation.CuentaBanco)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("CuentaBanco");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Cheque.DetailsClass.IImplementation.Beneficiario
        {
            get
            {
                return this.Beneficiario;
            }
            set
            {
                this.Beneficiario = (global::ApplicationData.Implementation.Beneficiario)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Beneficiario");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Cheque.DetailsClass.IImplementation.Cobrador
        {
            get
            {
                return this.Cobrador;
            }
            set
            {
                this.Cobrador = (global::ApplicationData.Implementation.Cobrador)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Cobrador");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Cheque.DetailsClass.IImplementation.Girador
        {
            get
            {
                return this.Girador;
            }
            set
            {
                this.Girador = (global::ApplicationData.Implementation.Girador)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Girador");
                }
            }
        }
        
        partial void OnCheque_CuentaBancoChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("CuentaBanco");
            }
        }
        
        partial void OnCheque_BeneficiarioChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Beneficiario");
            }
        }
        
        partial void OnCheque_CobradorChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Cobrador");
            }
        }
        
        partial void OnCheque_GiradorChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Girador");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class CuentaBanco :
        global::LightSwitchApplication.CuentaBanco.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.CuentaBanco.DetailsClass.IImplementation.Banco
        {
            get
            {
                return this.Banco;
            }
            set
            {
                this.Banco = (global::ApplicationData.Implementation.Banco)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Banco");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.CuentaBanco.DetailsClass.IImplementation.Cheques
        {
            get
            {
                return this.Cheques;
            }
        }
        
        partial void OnCuentaBanco_BancoChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Banco");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Beneficiario :
        global::LightSwitchApplication.Beneficiario.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Beneficiario.DetailsClass.IImplementation.Cheques
        {
            get
            {
                return this.Cheques;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Cobrador :
        global::LightSwitchApplication.Cobrador.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Cobrador.DetailsClass.IImplementation.Cheques
        {
            get
            {
                return this.Cheques;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Email :
        global::LightSwitchApplication.Email.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Banco :
        global::LightSwitchApplication.Banco.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Banco.DetailsClass.IImplementation.CuentaBancos
        {
            get
            {
                return this.CuentaBancos;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Girador :
        global::LightSwitchApplication.Girador.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Girador.DetailsClass.IImplementation.Cheques
        {
            get
            {
                return this.Cheques;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class SendMail :
        global::LightSwitchApplication.SendMail.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Secuencia :
        global::LightSwitchApplication.Secuencia.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Log :
        global::LightSwitchApplication.Log.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class OperacionEMail :
        global::LightSwitchApplication.OperacionEMail.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Parametro :
        global::LightSwitchApplication.Parametro.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
}

