

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class Log : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Log entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Log()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Log(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Log> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Log.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Log_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Log_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Log.DetailsClass.GetValue(this, global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Log.DetailsClass.SetValue(this, global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Log.DetailsClass.GetValue(this, global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Log.DetailsClass.SetValue(this, global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return global::LightSwitchApplication.Log.DetailsClass.GetValue(this, global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties.Fecha);
            }
            set
            {
                global::LightSwitchApplication.Log.DetailsClass.SetValue(this, global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties.Fecha, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fecha_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fecha_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fecha_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Usuario
        {
            get
            {
                return global::LightSwitchApplication.Log.DetailsClass.GetValue(this, global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties.Usuario);
            }
            set
            {
                global::LightSwitchApplication.Log.DetailsClass.SetValue(this, global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties.Usuario, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Usuario_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Usuario_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Usuario_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Objeto
        {
            get
            {
                return global::LightSwitchApplication.Log.DetailsClass.GetValue(this, global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties.Objeto);
            }
            set
            {
                global::LightSwitchApplication.Log.DetailsClass.SetValue(this, global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties.Objeto, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Objeto_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Objeto_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Objeto_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Metodo
        {
            get
            {
                return global::LightSwitchApplication.Log.DetailsClass.GetValue(this, global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties.Metodo);
            }
            set
            {
                global::LightSwitchApplication.Log.DetailsClass.SetValue(this, global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties.Metodo, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Metodo_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Metodo_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Metodo_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Detalle
        {
            get
            {
                return global::LightSwitchApplication.Log.DetailsClass.GetValue(this, global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties.Detalle);
            }
            set
            {
                global::LightSwitchApplication.Log.DetailsClass.SetValue(this, global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties.Detalle, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Detalle_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Detalle_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Detalle_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Log,
                global::LightSwitchApplication.Log.DetailsClass,
                global::LightSwitchApplication.Log.DetailsClass.IImplementation,
                global::LightSwitchApplication.Log.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass>.Entry
                __LogEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass>.Entry(
                    global::LightSwitchApplication.Log.DetailsClass.__Log_CreateNew,
                    global::LightSwitchApplication.Log.DetailsClass.__Log_Created,
                    global::LightSwitchApplication.Log.DetailsClass.__Log_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Log __Log_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Log> es)
            {
                return new global::LightSwitchApplication.Log(es);
            }
            private static void __Log_Created(global::LightSwitchApplication.Log e)
            {
                e.Log_Created();
            }
            private static bool __Log_AllowSaveWithErrors(global::LightSwitchApplication.Log e)
            {
                bool result = false;
                e.Log_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Log.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, global::System.DateTime> Fecha
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties.Fecha) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, string> Usuario
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties.Usuario) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, string> Objeto
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties.Objeto) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, string> Metodo
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties.Metodo) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, string> Detalle
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties.Detalle) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new global::System.DateTime Fecha { get; set; }
                new string Usuario { get; set; }
                new string Objeto { get; set; }
                new string Metodo { get; set; }
                new string Detalle { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Log.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, int>.Data> c, global::LightSwitchApplication.Log.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Log e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Log e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Log.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Log.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Log e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Log.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Log.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Log e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Log e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Log.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Log.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Log e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, global::System.DateTime>.Entry
                    Fecha = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, global::System.DateTime>.Entry(
                        "Fecha",
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Fecha_Stub,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Fecha_ComputeIsReadOnly,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Fecha_Validate,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Fecha_GetImplementationValue,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Fecha_SetImplementationValue,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Fecha_OnValueChanged);
                private static void _Fecha_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Log.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Log.DetailsClass d, object sf)
                {
                    c(d, ref d._Fecha, sf);
                }
                private static bool _Fecha_ComputeIsReadOnly(global::LightSwitchApplication.Log e)
                {
                    bool result = false;
                    e.Fecha_IsReadOnly(ref result);
                    return result;
                }
                private static void _Fecha_Validate(global::LightSwitchApplication.Log e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Fecha_Validate(r);
                }
                private static global::System.DateTime _Fecha_GetImplementationValue(global::LightSwitchApplication.Log.DetailsClass d)
                {
                    return d.ImplementationEntity.Fecha;
                }
                private static void _Fecha_SetImplementationValue(global::LightSwitchApplication.Log.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.Fecha = global::LightSwitchApplication.Log.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _Fecha_OnValueChanged(global::LightSwitchApplication.Log e)
                {
                    e.Fecha_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, string>.Entry
                    Usuario = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, string>.Entry(
                        "Usuario",
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Usuario_Stub,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Usuario_ComputeIsReadOnly,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Usuario_Validate,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Usuario_GetImplementationValue,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Usuario_SetImplementationValue,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Usuario_OnValueChanged);
                private static void _Usuario_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Log.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, string>.Data> c, global::LightSwitchApplication.Log.DetailsClass d, object sf)
                {
                    c(d, ref d._Usuario, sf);
                }
                private static bool _Usuario_ComputeIsReadOnly(global::LightSwitchApplication.Log e)
                {
                    bool result = false;
                    e.Usuario_IsReadOnly(ref result);
                    return result;
                }
                private static void _Usuario_Validate(global::LightSwitchApplication.Log e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Usuario_Validate(r);
                }
                private static string _Usuario_GetImplementationValue(global::LightSwitchApplication.Log.DetailsClass d)
                {
                    return d.ImplementationEntity.Usuario;
                }
                private static void _Usuario_SetImplementationValue(global::LightSwitchApplication.Log.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Usuario = v;
                }
                private static void _Usuario_OnValueChanged(global::LightSwitchApplication.Log e)
                {
                    e.Usuario_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, string>.Entry
                    Objeto = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, string>.Entry(
                        "Objeto",
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Objeto_Stub,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Objeto_ComputeIsReadOnly,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Objeto_Validate,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Objeto_GetImplementationValue,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Objeto_SetImplementationValue,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Objeto_OnValueChanged);
                private static void _Objeto_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Log.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, string>.Data> c, global::LightSwitchApplication.Log.DetailsClass d, object sf)
                {
                    c(d, ref d._Objeto, sf);
                }
                private static bool _Objeto_ComputeIsReadOnly(global::LightSwitchApplication.Log e)
                {
                    bool result = false;
                    e.Objeto_IsReadOnly(ref result);
                    return result;
                }
                private static void _Objeto_Validate(global::LightSwitchApplication.Log e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Objeto_Validate(r);
                }
                private static string _Objeto_GetImplementationValue(global::LightSwitchApplication.Log.DetailsClass d)
                {
                    return d.ImplementationEntity.Objeto;
                }
                private static void _Objeto_SetImplementationValue(global::LightSwitchApplication.Log.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Objeto = v;
                }
                private static void _Objeto_OnValueChanged(global::LightSwitchApplication.Log e)
                {
                    e.Objeto_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, string>.Entry
                    Metodo = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, string>.Entry(
                        "Metodo",
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Metodo_Stub,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Metodo_ComputeIsReadOnly,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Metodo_Validate,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Metodo_GetImplementationValue,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Metodo_SetImplementationValue,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Metodo_OnValueChanged);
                private static void _Metodo_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Log.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, string>.Data> c, global::LightSwitchApplication.Log.DetailsClass d, object sf)
                {
                    c(d, ref d._Metodo, sf);
                }
                private static bool _Metodo_ComputeIsReadOnly(global::LightSwitchApplication.Log e)
                {
                    bool result = false;
                    e.Metodo_IsReadOnly(ref result);
                    return result;
                }
                private static void _Metodo_Validate(global::LightSwitchApplication.Log e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Metodo_Validate(r);
                }
                private static string _Metodo_GetImplementationValue(global::LightSwitchApplication.Log.DetailsClass d)
                {
                    return d.ImplementationEntity.Metodo;
                }
                private static void _Metodo_SetImplementationValue(global::LightSwitchApplication.Log.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Metodo = v;
                }
                private static void _Metodo_OnValueChanged(global::LightSwitchApplication.Log e)
                {
                    e.Metodo_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, string>.Entry
                    Detalle = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, string>.Entry(
                        "Detalle",
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Detalle_Stub,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Detalle_ComputeIsReadOnly,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Detalle_Validate,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Detalle_GetImplementationValue,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Detalle_SetImplementationValue,
                        global::LightSwitchApplication.Log.DetailsClass.PropertySetProperties._Detalle_OnValueChanged);
                private static void _Detalle_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Log.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, string>.Data> c, global::LightSwitchApplication.Log.DetailsClass d, object sf)
                {
                    c(d, ref d._Detalle, sf);
                }
                private static bool _Detalle_ComputeIsReadOnly(global::LightSwitchApplication.Log e)
                {
                    bool result = false;
                    e.Detalle_IsReadOnly(ref result);
                    return result;
                }
                private static void _Detalle_Validate(global::LightSwitchApplication.Log e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Detalle_Validate(r);
                }
                private static string _Detalle_GetImplementationValue(global::LightSwitchApplication.Log.DetailsClass d)
                {
                    return d.ImplementationEntity.Detalle;
                }
                private static void _Detalle_SetImplementationValue(global::LightSwitchApplication.Log.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Detalle = v;
                }
                private static void _Detalle_OnValueChanged(global::LightSwitchApplication.Log e)
                {
                    e.Detalle_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, global::System.DateTime>.Data _Fecha;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, string>.Data _Usuario;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, string>.Data _Objeto;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, string>.Data _Metodo;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Log, global::LightSwitchApplication.Log.DetailsClass, string>.Data _Detalle;
            
        }
    
        #endregion
    }
    
    #endregion
}
