

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class Secuencia : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Secuencia entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Secuencia()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Secuencia(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Secuencia> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Secuencia.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Secuencia_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Secuencia_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Secuencia.DetailsClass.GetValue(this, global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Secuencia.DetailsClass.SetValue(this, global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Secuencia.DetailsClass.GetValue(this, global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Secuencia.DetailsClass.SetValue(this, global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Catagoria
        {
            get
            {
                return global::LightSwitchApplication.Secuencia.DetailsClass.GetValue(this, global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties.Catagoria);
            }
            set
            {
                global::LightSwitchApplication.Secuencia.DetailsClass.SetValue(this, global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties.Catagoria, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Catagoria_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Catagoria_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Catagoria_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Clave
        {
            get
            {
                return global::LightSwitchApplication.Secuencia.DetailsClass.GetValue(this, global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties.Clave);
            }
            set
            {
                global::LightSwitchApplication.Secuencia.DetailsClass.SetValue(this, global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties.Clave, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Clave_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Clave_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Clave_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int NroActual
        {
            get
            {
                return global::LightSwitchApplication.Secuencia.DetailsClass.GetValue(this, global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties.NroActual);
            }
            set
            {
                global::LightSwitchApplication.Secuencia.DetailsClass.SetValue(this, global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties.NroActual, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NroActual_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NroActual_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NroActual_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> NroInicial
        {
            get
            {
                return global::LightSwitchApplication.Secuencia.DetailsClass.GetValue(this, global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties.NroInicial);
            }
            set
            {
                global::LightSwitchApplication.Secuencia.DetailsClass.SetValue(this, global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties.NroInicial, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NroInicial_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NroInicial_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NroInicial_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> NroFinal
        {
            get
            {
                return global::LightSwitchApplication.Secuencia.DetailsClass.GetValue(this, global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties.NroFinal);
            }
            set
            {
                global::LightSwitchApplication.Secuencia.DetailsClass.SetValue(this, global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties.NroFinal, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NroFinal_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NroFinal_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NroFinal_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Secuencia,
                global::LightSwitchApplication.Secuencia.DetailsClass,
                global::LightSwitchApplication.Secuencia.DetailsClass.IImplementation,
                global::LightSwitchApplication.Secuencia.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass>.Entry
                __SecuenciaEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass>.Entry(
                    global::LightSwitchApplication.Secuencia.DetailsClass.__Secuencia_CreateNew,
                    global::LightSwitchApplication.Secuencia.DetailsClass.__Secuencia_Created,
                    global::LightSwitchApplication.Secuencia.DetailsClass.__Secuencia_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Secuencia __Secuencia_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Secuencia> es)
            {
                return new global::LightSwitchApplication.Secuencia(es);
            }
            private static void __Secuencia_Created(global::LightSwitchApplication.Secuencia e)
            {
                e.Secuencia_Created();
            }
            private static bool __Secuencia_AllowSaveWithErrors(global::LightSwitchApplication.Secuencia e)
            {
                bool result = false;
                e.Secuencia_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Secuencia.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, string> Catagoria
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties.Catagoria) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, string> Clave
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties.Clave) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, int> NroActual
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties.NroActual) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, global::System.Nullable<int>> NroInicial
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties.NroInicial) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, global::System.Nullable<int>> NroFinal
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties.NroFinal) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new string Catagoria { get; set; }
                new string Clave { get; set; }
                new int NroActual { get; set; }
                new global::System.Nullable<int> NroInicial { get; set; }
                new global::System.Nullable<int> NroFinal { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Secuencia.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, int>.Data> c, global::LightSwitchApplication.Secuencia.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Secuencia e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Secuencia e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Secuencia.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Secuencia.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Secuencia e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Secuencia.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Secuencia.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Secuencia e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Secuencia e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Secuencia.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Secuencia.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Secuencia e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, string>.Entry
                    Catagoria = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, string>.Entry(
                        "Catagoria",
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._Catagoria_Stub,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._Catagoria_ComputeIsReadOnly,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._Catagoria_Validate,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._Catagoria_GetImplementationValue,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._Catagoria_SetImplementationValue,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._Catagoria_OnValueChanged);
                private static void _Catagoria_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Secuencia.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, string>.Data> c, global::LightSwitchApplication.Secuencia.DetailsClass d, object sf)
                {
                    c(d, ref d._Catagoria, sf);
                }
                private static bool _Catagoria_ComputeIsReadOnly(global::LightSwitchApplication.Secuencia e)
                {
                    bool result = false;
                    e.Catagoria_IsReadOnly(ref result);
                    return result;
                }
                private static void _Catagoria_Validate(global::LightSwitchApplication.Secuencia e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Catagoria_Validate(r);
                }
                private static string _Catagoria_GetImplementationValue(global::LightSwitchApplication.Secuencia.DetailsClass d)
                {
                    return d.ImplementationEntity.Catagoria;
                }
                private static void _Catagoria_SetImplementationValue(global::LightSwitchApplication.Secuencia.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Catagoria = v;
                }
                private static void _Catagoria_OnValueChanged(global::LightSwitchApplication.Secuencia e)
                {
                    e.Catagoria_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, string>.Entry
                    Clave = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, string>.Entry(
                        "Clave",
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._Clave_Stub,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._Clave_ComputeIsReadOnly,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._Clave_Validate,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._Clave_GetImplementationValue,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._Clave_SetImplementationValue,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._Clave_OnValueChanged);
                private static void _Clave_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Secuencia.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, string>.Data> c, global::LightSwitchApplication.Secuencia.DetailsClass d, object sf)
                {
                    c(d, ref d._Clave, sf);
                }
                private static bool _Clave_ComputeIsReadOnly(global::LightSwitchApplication.Secuencia e)
                {
                    bool result = false;
                    e.Clave_IsReadOnly(ref result);
                    return result;
                }
                private static void _Clave_Validate(global::LightSwitchApplication.Secuencia e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Clave_Validate(r);
                }
                private static string _Clave_GetImplementationValue(global::LightSwitchApplication.Secuencia.DetailsClass d)
                {
                    return d.ImplementationEntity.Clave;
                }
                private static void _Clave_SetImplementationValue(global::LightSwitchApplication.Secuencia.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Clave = v;
                }
                private static void _Clave_OnValueChanged(global::LightSwitchApplication.Secuencia e)
                {
                    e.Clave_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, int>.Entry
                    NroActual = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, int>.Entry(
                        "NroActual",
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._NroActual_Stub,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._NroActual_ComputeIsReadOnly,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._NroActual_Validate,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._NroActual_GetImplementationValue,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._NroActual_SetImplementationValue,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._NroActual_OnValueChanged);
                private static void _NroActual_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Secuencia.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, int>.Data> c, global::LightSwitchApplication.Secuencia.DetailsClass d, object sf)
                {
                    c(d, ref d._NroActual, sf);
                }
                private static bool _NroActual_ComputeIsReadOnly(global::LightSwitchApplication.Secuencia e)
                {
                    bool result = false;
                    e.NroActual_IsReadOnly(ref result);
                    return result;
                }
                private static void _NroActual_Validate(global::LightSwitchApplication.Secuencia e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.NroActual_Validate(r);
                }
                private static int _NroActual_GetImplementationValue(global::LightSwitchApplication.Secuencia.DetailsClass d)
                {
                    return d.ImplementationEntity.NroActual;
                }
                private static void _NroActual_SetImplementationValue(global::LightSwitchApplication.Secuencia.DetailsClass d, int v)
                {
                    d.ImplementationEntity.NroActual = v;
                }
                private static void _NroActual_OnValueChanged(global::LightSwitchApplication.Secuencia e)
                {
                    e.NroActual_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, global::System.Nullable<int>>.Entry
                    NroInicial = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, global::System.Nullable<int>>.Entry(
                        "NroInicial",
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._NroInicial_Stub,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._NroInicial_ComputeIsReadOnly,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._NroInicial_Validate,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._NroInicial_GetImplementationValue,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._NroInicial_SetImplementationValue,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._NroInicial_OnValueChanged);
                private static void _NroInicial_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Secuencia.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.Secuencia.DetailsClass d, object sf)
                {
                    c(d, ref d._NroInicial, sf);
                }
                private static bool _NroInicial_ComputeIsReadOnly(global::LightSwitchApplication.Secuencia e)
                {
                    bool result = false;
                    e.NroInicial_IsReadOnly(ref result);
                    return result;
                }
                private static void _NroInicial_Validate(global::LightSwitchApplication.Secuencia e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.NroInicial_Validate(r);
                }
                private static global::System.Nullable<int> _NroInicial_GetImplementationValue(global::LightSwitchApplication.Secuencia.DetailsClass d)
                {
                    return d.ImplementationEntity.NroInicial;
                }
                private static void _NroInicial_SetImplementationValue(global::LightSwitchApplication.Secuencia.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.NroInicial = v;
                }
                private static void _NroInicial_OnValueChanged(global::LightSwitchApplication.Secuencia e)
                {
                    e.NroInicial_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, global::System.Nullable<int>>.Entry
                    NroFinal = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, global::System.Nullable<int>>.Entry(
                        "NroFinal",
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._NroFinal_Stub,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._NroFinal_ComputeIsReadOnly,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._NroFinal_Validate,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._NroFinal_GetImplementationValue,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._NroFinal_SetImplementationValue,
                        global::LightSwitchApplication.Secuencia.DetailsClass.PropertySetProperties._NroFinal_OnValueChanged);
                private static void _NroFinal_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Secuencia.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.Secuencia.DetailsClass d, object sf)
                {
                    c(d, ref d._NroFinal, sf);
                }
                private static bool _NroFinal_ComputeIsReadOnly(global::LightSwitchApplication.Secuencia e)
                {
                    bool result = false;
                    e.NroFinal_IsReadOnly(ref result);
                    return result;
                }
                private static void _NroFinal_Validate(global::LightSwitchApplication.Secuencia e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.NroFinal_Validate(r);
                }
                private static global::System.Nullable<int> _NroFinal_GetImplementationValue(global::LightSwitchApplication.Secuencia.DetailsClass d)
                {
                    return d.ImplementationEntity.NroFinal;
                }
                private static void _NroFinal_SetImplementationValue(global::LightSwitchApplication.Secuencia.DetailsClass d, global::System.Nullable<int> v)
                {
                    d.ImplementationEntity.NroFinal = v;
                }
                private static void _NroFinal_OnValueChanged(global::LightSwitchApplication.Secuencia e)
                {
                    e.NroFinal_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, string>.Data _Catagoria;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, string>.Data _Clave;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, int>.Data _NroActual;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, global::System.Nullable<int>>.Data _NroInicial;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Secuencia, global::LightSwitchApplication.Secuencia.DetailsClass, global::System.Nullable<int>>.Data _NroFinal;
            
        }
    
        #endregion
    }
    
    #endregion
}
