

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class CuentaBanco : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the CuentaBanco entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public CuentaBanco()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public CuentaBanco(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.CuentaBanco> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.CuentaBanco.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CuentaBanco_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CuentaBanco_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.CuentaBanco.DetailsClass.GetValue(this, global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.CuentaBanco.DetailsClass.SetValue(this, global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.CuentaBanco.DetailsClass.GetValue(this, global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.CuentaBanco.DetailsClass.SetValue(this, global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CuentaNro
        {
            get
            {
                return global::LightSwitchApplication.CuentaBanco.DetailsClass.GetValue(this, global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties.CuentaNro);
            }
            set
            {
                global::LightSwitchApplication.CuentaBanco.DetailsClass.SetValue(this, global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties.CuentaNro, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CuentaNro_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CuentaNro_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CuentaNro_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Moneda
        {
            get
            {
                return global::LightSwitchApplication.CuentaBanco.DetailsClass.GetValue(this, global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties.Moneda);
            }
            set
            {
                global::LightSwitchApplication.CuentaBanco.DetailsClass.SetValue(this, global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties.Moneda, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Moneda_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Moneda_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Moneda_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Identidad
        {
            get
            {
                return global::LightSwitchApplication.CuentaBanco.DetailsClass.GetValue(this, global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties.Identidad);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Identidad_Compute(ref string result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Identidad_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Banco Banco
        {
            get
            {
                return global::LightSwitchApplication.CuentaBanco.DetailsClass.GetValue(this, global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties.Banco);
            }
            set
            {
                global::LightSwitchApplication.CuentaBanco.DetailsClass.SetValue(this, global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties.Banco, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Banco_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Banco_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Banco_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Cheque> Cheques
        {
            get
            {
                return global::LightSwitchApplication.CuentaBanco.DetailsClass.GetValue(this, global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties.Cheques);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Cheque> ChequesQuery
        {
            get
            {
                return global::LightSwitchApplication.CuentaBanco.DetailsClass.GetQuery(this, global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties.Cheques);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.CuentaBanco,
                global::LightSwitchApplication.CuentaBanco.DetailsClass,
                global::LightSwitchApplication.CuentaBanco.DetailsClass.IImplementation,
                global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass>.Entry
                __CuentaBancoEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass>.Entry(
                    global::LightSwitchApplication.CuentaBanco.DetailsClass.__CuentaBanco_CreateNew,
                    global::LightSwitchApplication.CuentaBanco.DetailsClass.__CuentaBanco_Created,
                    global::LightSwitchApplication.CuentaBanco.DetailsClass.__CuentaBanco_AllowSaveWithErrors);
            private static global::LightSwitchApplication.CuentaBanco __CuentaBanco_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.CuentaBanco> es)
            {
                return new global::LightSwitchApplication.CuentaBanco(es);
            }
            private static void __CuentaBanco_Created(global::LightSwitchApplication.CuentaBanco e)
            {
                e.CuentaBanco_Created();
            }
            private static bool __CuentaBanco_AllowSaveWithErrors(global::LightSwitchApplication.CuentaBanco e)
            {
                bool result = false;
                e.CuentaBanco_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, string> CuentaNro
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties.CuentaNro) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, string> Moneda
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties.Moneda) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, string> Identidad
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties.Identidad) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, global::LightSwitchApplication.Banco> Banco
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties.Banco) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, global::LightSwitchApplication.Banco>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, global::LightSwitchApplication.Cheque> Cheques
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties.Cheques) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, global::LightSwitchApplication.Cheque>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new string CuentaNro { get; set; }
                new string Moneda { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Banco { get; set; }
                new global::System.Collections.IEnumerable Cheques { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CuentaBanco.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, int>.Data> c, global::LightSwitchApplication.CuentaBanco.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.CuentaBanco e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.CuentaBanco e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.CuentaBanco.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.CuentaBanco.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.CuentaBanco e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CuentaBanco.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.CuentaBanco.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.CuentaBanco e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.CuentaBanco e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.CuentaBanco.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.CuentaBanco.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.CuentaBanco e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, string>.Entry
                    CuentaNro = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, string>.Entry(
                        "CuentaNro",
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._CuentaNro_Stub,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._CuentaNro_ComputeIsReadOnly,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._CuentaNro_Validate,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._CuentaNro_GetImplementationValue,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._CuentaNro_SetImplementationValue,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._CuentaNro_OnValueChanged);
                private static void _CuentaNro_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CuentaBanco.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, string>.Data> c, global::LightSwitchApplication.CuentaBanco.DetailsClass d, object sf)
                {
                    c(d, ref d._CuentaNro, sf);
                }
                private static bool _CuentaNro_ComputeIsReadOnly(global::LightSwitchApplication.CuentaBanco e)
                {
                    bool result = false;
                    e.CuentaNro_IsReadOnly(ref result);
                    return result;
                }
                private static void _CuentaNro_Validate(global::LightSwitchApplication.CuentaBanco e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CuentaNro_Validate(r);
                }
                private static string _CuentaNro_GetImplementationValue(global::LightSwitchApplication.CuentaBanco.DetailsClass d)
                {
                    return d.ImplementationEntity.CuentaNro;
                }
                private static void _CuentaNro_SetImplementationValue(global::LightSwitchApplication.CuentaBanco.DetailsClass d, string v)
                {
                    d.ImplementationEntity.CuentaNro = v;
                }
                private static void _CuentaNro_OnValueChanged(global::LightSwitchApplication.CuentaBanco e)
                {
                    e.CuentaNro_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, string>.Entry
                    Moneda = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, string>.Entry(
                        "Moneda",
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Moneda_Stub,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Moneda_ComputeIsReadOnly,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Moneda_Validate,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Moneda_GetImplementationValue,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Moneda_SetImplementationValue,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Moneda_OnValueChanged);
                private static void _Moneda_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CuentaBanco.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, string>.Data> c, global::LightSwitchApplication.CuentaBanco.DetailsClass d, object sf)
                {
                    c(d, ref d._Moneda, sf);
                }
                private static bool _Moneda_ComputeIsReadOnly(global::LightSwitchApplication.CuentaBanco e)
                {
                    bool result = false;
                    e.Moneda_IsReadOnly(ref result);
                    return result;
                }
                private static void _Moneda_Validate(global::LightSwitchApplication.CuentaBanco e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Moneda_Validate(r);
                }
                private static string _Moneda_GetImplementationValue(global::LightSwitchApplication.CuentaBanco.DetailsClass d)
                {
                    return d.ImplementationEntity.Moneda;
                }
                private static void _Moneda_SetImplementationValue(global::LightSwitchApplication.CuentaBanco.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Moneda = v;
                }
                private static void _Moneda_OnValueChanged(global::LightSwitchApplication.CuentaBanco e)
                {
                    e.Moneda_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, string>.Entry
                    Identidad = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, string>.Entry(
                        "Identidad",
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Identidad_Stub,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Identidad_Validate,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Identidad_ComputeValue);
                private static void _Identidad_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CuentaBanco.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, string>.Data> c, global::LightSwitchApplication.CuentaBanco.DetailsClass d, object sf)
                {
                    c(d, ref d._Identidad, sf);
                }
                private static void _Identidad_Validate(global::LightSwitchApplication.CuentaBanco e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Identidad_Validate(r);
                }
                private static string _Identidad_ComputeValue(global::LightSwitchApplication.CuentaBanco e)
                {
                    string value = default(string);
                    e.Identidad_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, global::LightSwitchApplication.Banco>.Entry
                    Banco = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, global::LightSwitchApplication.Banco>.Entry(
                        "Banco",
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Banco_Stub,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Banco_ComputeIsReadOnly,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Banco_Validate,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Banco_GetCoreImplementationValue,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Banco_GetImplementationValue,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Banco_SetImplementationValue,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Banco_Refresh,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Banco_OnValueChanged);
                private static void _Banco_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CuentaBanco.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, global::LightSwitchApplication.Banco>.Data> c, global::LightSwitchApplication.CuentaBanco.DetailsClass d, object sf)
                {
                    c(d, ref d._Banco, sf);
                }
                private static bool _Banco_ComputeIsReadOnly(global::LightSwitchApplication.CuentaBanco e)
                {
                    bool result = false;
                    e.Banco_IsReadOnly(ref result);
                    return result;
                }
                private static void _Banco_Validate(global::LightSwitchApplication.CuentaBanco e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Banco_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Banco_GetCoreImplementationValue(global::LightSwitchApplication.CuentaBanco.DetailsClass d)
                {
                    return d.ImplementationEntity.Banco;
                }
                private static global::LightSwitchApplication.Banco _Banco_GetImplementationValue(global::LightSwitchApplication.CuentaBanco.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Banco, global::LightSwitchApplication.Banco.DetailsClass>(global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties.Banco, ref d._Banco);
                }
                private static void _Banco_SetImplementationValue(global::LightSwitchApplication.CuentaBanco.DetailsClass d, global::LightSwitchApplication.Banco v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties.Banco, ref d._Banco, (i, ev) => i.Banco = ev, v);
                }
                private static void _Banco_Refresh(global::LightSwitchApplication.CuentaBanco.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties.Banco, ref d._Banco);
                }
                private static void _Banco_OnValueChanged(global::LightSwitchApplication.CuentaBanco e)
                {
                    e.Banco_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, global::LightSwitchApplication.Cheque>.Entry
                    Cheques = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, global::LightSwitchApplication.Cheque>.Entry(
                        "Cheques",
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Cheques_Stub,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Cheques_GetReferencedEntities,
                        global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties._Cheques_GetEntityCollection);
                private static void _Cheques_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CuentaBanco.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, global::LightSwitchApplication.Cheque>.Data> c, global::LightSwitchApplication.CuentaBanco.DetailsClass d, object sf)
                {
                    c(d, ref d._Cheques, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Cheque> _Cheques_GetReferencedEntities(global::LightSwitchApplication.CuentaBanco.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Cheque, global::LightSwitchApplication.Cheque.DetailsClass>(global::LightSwitchApplication.CuentaBanco.DetailsClass.PropertySetProperties.Cheques, ref d._Cheques);
                }
                private static global::System.Collections.IEnumerable _Cheques_GetEntityCollection(global::LightSwitchApplication.CuentaBanco.DetailsClass d)
                {
                    return d.ImplementationEntity.Cheques;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, string>.Data _CuentaNro;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, string>.Data _Moneda;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, string>.Data _Identidad;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, global::LightSwitchApplication.Banco>.Data _Banco;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.CuentaBanco, global::LightSwitchApplication.CuentaBanco.DetailsClass, global::LightSwitchApplication.Cheque>.Data _Cheques;
            
        }
    
        #endregion
    }
    
    #endregion
}
