

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class SendMail : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the SendMail entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public SendMail()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public SendMail(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.SendMail> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.SendMail.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SendMail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SendMail_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.SendMail.DetailsClass.GetValue(this, global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.SendMail.DetailsClass.SetValue(this, global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.SendMail.DetailsClass.GetValue(this, global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.SendMail.DetailsClass.SetValue(this, global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return global::LightSwitchApplication.SendMail.DetailsClass.GetValue(this, global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.Fecha);
            }
            set
            {
                global::LightSwitchApplication.SendMail.DetailsClass.SetValue(this, global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.Fecha, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fecha_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fecha_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Fecha_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string RolMail
        {
            get
            {
                return global::LightSwitchApplication.SendMail.DetailsClass.GetValue(this, global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.RolMail);
            }
            set
            {
                global::LightSwitchApplication.SendMail.DetailsClass.SetValue(this, global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.RolMail, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RolMail_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RolMail_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RolMail_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MailTo
        {
            get
            {
                return global::LightSwitchApplication.SendMail.DetailsClass.GetValue(this, global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.MailTo);
            }
            set
            {
                global::LightSwitchApplication.SendMail.DetailsClass.SetValue(this, global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.MailTo, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MailTo_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MailTo_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MailTo_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MailFrom
        {
            get
            {
                return global::LightSwitchApplication.SendMail.DetailsClass.GetValue(this, global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.MailFrom);
            }
            set
            {
                global::LightSwitchApplication.SendMail.DetailsClass.SetValue(this, global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.MailFrom, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MailFrom_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MailFrom_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MailFrom_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Subject
        {
            get
            {
                return global::LightSwitchApplication.SendMail.DetailsClass.GetValue(this, global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.Subject);
            }
            set
            {
                global::LightSwitchApplication.SendMail.DetailsClass.SetValue(this, global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.Subject, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Subject_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Subject_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Subject_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Body
        {
            get
            {
                return global::LightSwitchApplication.SendMail.DetailsClass.GetValue(this, global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.Body);
            }
            set
            {
                global::LightSwitchApplication.SendMail.DetailsClass.SetValue(this, global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.Body, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Body_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Body_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Body_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Codigo
        {
            get
            {
                return global::LightSwitchApplication.SendMail.DetailsClass.GetValue(this, global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.Codigo);
            }
            set
            {
                global::LightSwitchApplication.SendMail.DetailsClass.SetValue(this, global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.Codigo, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Codigo_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Codigo_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Codigo_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.SendMail,
                global::LightSwitchApplication.SendMail.DetailsClass,
                global::LightSwitchApplication.SendMail.DetailsClass.IImplementation,
                global::LightSwitchApplication.SendMail.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass>.Entry
                __SendMailEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass>.Entry(
                    global::LightSwitchApplication.SendMail.DetailsClass.__SendMail_CreateNew,
                    global::LightSwitchApplication.SendMail.DetailsClass.__SendMail_Created,
                    global::LightSwitchApplication.SendMail.DetailsClass.__SendMail_AllowSaveWithErrors);
            private static global::LightSwitchApplication.SendMail __SendMail_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.SendMail> es)
            {
                return new global::LightSwitchApplication.SendMail(es);
            }
            private static void __SendMail_Created(global::LightSwitchApplication.SendMail e)
            {
                e.SendMail_Created();
            }
            private static bool __SendMail_AllowSaveWithErrors(global::LightSwitchApplication.SendMail e)
            {
                bool result = false;
                e.SendMail_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.SendMail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, global::System.DateTime> Fecha
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.Fecha) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string> RolMail
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.RolMail) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string> MailTo
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.MailTo) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string> MailFrom
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.MailFrom) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string> Subject
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.Subject) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string> Body
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.Body) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string> Codigo
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties.Codigo) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new global::System.DateTime Fecha { get; set; }
                new string RolMail { get; set; }
                new string MailTo { get; set; }
                new string MailFrom { get; set; }
                new string Subject { get; set; }
                new string Body { get; set; }
                new string Codigo { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SendMail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, int>.Data> c, global::LightSwitchApplication.SendMail.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.SendMail e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.SendMail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.SendMail.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.SendMail.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.SendMail e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SendMail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.SendMail.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.SendMail e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.SendMail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.SendMail.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.SendMail.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.SendMail e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, global::System.DateTime>.Entry
                    Fecha = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, global::System.DateTime>.Entry(
                        "Fecha",
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Fecha_Stub,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Fecha_ComputeIsReadOnly,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Fecha_Validate,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Fecha_GetImplementationValue,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Fecha_SetImplementationValue,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Fecha_OnValueChanged);
                private static void _Fecha_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SendMail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.SendMail.DetailsClass d, object sf)
                {
                    c(d, ref d._Fecha, sf);
                }
                private static bool _Fecha_ComputeIsReadOnly(global::LightSwitchApplication.SendMail e)
                {
                    bool result = false;
                    e.Fecha_IsReadOnly(ref result);
                    return result;
                }
                private static void _Fecha_Validate(global::LightSwitchApplication.SendMail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Fecha_Validate(r);
                }
                private static global::System.DateTime _Fecha_GetImplementationValue(global::LightSwitchApplication.SendMail.DetailsClass d)
                {
                    return d.ImplementationEntity.Fecha;
                }
                private static void _Fecha_SetImplementationValue(global::LightSwitchApplication.SendMail.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.Fecha = global::LightSwitchApplication.SendMail.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _Fecha_OnValueChanged(global::LightSwitchApplication.SendMail e)
                {
                    e.Fecha_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>.Entry
                    RolMail = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>.Entry(
                        "RolMail",
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._RolMail_Stub,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._RolMail_ComputeIsReadOnly,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._RolMail_Validate,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._RolMail_GetImplementationValue,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._RolMail_SetImplementationValue,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._RolMail_OnValueChanged);
                private static void _RolMail_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SendMail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>.Data> c, global::LightSwitchApplication.SendMail.DetailsClass d, object sf)
                {
                    c(d, ref d._RolMail, sf);
                }
                private static bool _RolMail_ComputeIsReadOnly(global::LightSwitchApplication.SendMail e)
                {
                    bool result = false;
                    e.RolMail_IsReadOnly(ref result);
                    return result;
                }
                private static void _RolMail_Validate(global::LightSwitchApplication.SendMail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RolMail_Validate(r);
                }
                private static string _RolMail_GetImplementationValue(global::LightSwitchApplication.SendMail.DetailsClass d)
                {
                    return d.ImplementationEntity.RolMail;
                }
                private static void _RolMail_SetImplementationValue(global::LightSwitchApplication.SendMail.DetailsClass d, string v)
                {
                    d.ImplementationEntity.RolMail = v;
                }
                private static void _RolMail_OnValueChanged(global::LightSwitchApplication.SendMail e)
                {
                    e.RolMail_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>.Entry
                    MailTo = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>.Entry(
                        "MailTo",
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._MailTo_Stub,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._MailTo_ComputeIsReadOnly,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._MailTo_Validate,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._MailTo_GetImplementationValue,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._MailTo_SetImplementationValue,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._MailTo_OnValueChanged);
                private static void _MailTo_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SendMail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>.Data> c, global::LightSwitchApplication.SendMail.DetailsClass d, object sf)
                {
                    c(d, ref d._MailTo, sf);
                }
                private static bool _MailTo_ComputeIsReadOnly(global::LightSwitchApplication.SendMail e)
                {
                    bool result = false;
                    e.MailTo_IsReadOnly(ref result);
                    return result;
                }
                private static void _MailTo_Validate(global::LightSwitchApplication.SendMail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.MailTo_Validate(r);
                }
                private static string _MailTo_GetImplementationValue(global::LightSwitchApplication.SendMail.DetailsClass d)
                {
                    return d.ImplementationEntity.MailTo;
                }
                private static void _MailTo_SetImplementationValue(global::LightSwitchApplication.SendMail.DetailsClass d, string v)
                {
                    d.ImplementationEntity.MailTo = v;
                }
                private static void _MailTo_OnValueChanged(global::LightSwitchApplication.SendMail e)
                {
                    e.MailTo_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>.Entry
                    MailFrom = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>.Entry(
                        "MailFrom",
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._MailFrom_Stub,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._MailFrom_ComputeIsReadOnly,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._MailFrom_Validate,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._MailFrom_GetImplementationValue,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._MailFrom_SetImplementationValue,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._MailFrom_OnValueChanged);
                private static void _MailFrom_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SendMail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>.Data> c, global::LightSwitchApplication.SendMail.DetailsClass d, object sf)
                {
                    c(d, ref d._MailFrom, sf);
                }
                private static bool _MailFrom_ComputeIsReadOnly(global::LightSwitchApplication.SendMail e)
                {
                    bool result = false;
                    e.MailFrom_IsReadOnly(ref result);
                    return result;
                }
                private static void _MailFrom_Validate(global::LightSwitchApplication.SendMail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.MailFrom_Validate(r);
                }
                private static string _MailFrom_GetImplementationValue(global::LightSwitchApplication.SendMail.DetailsClass d)
                {
                    return d.ImplementationEntity.MailFrom;
                }
                private static void _MailFrom_SetImplementationValue(global::LightSwitchApplication.SendMail.DetailsClass d, string v)
                {
                    d.ImplementationEntity.MailFrom = v;
                }
                private static void _MailFrom_OnValueChanged(global::LightSwitchApplication.SendMail e)
                {
                    e.MailFrom_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>.Entry
                    Subject = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>.Entry(
                        "Subject",
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Subject_Stub,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Subject_ComputeIsReadOnly,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Subject_Validate,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Subject_GetImplementationValue,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Subject_SetImplementationValue,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Subject_OnValueChanged);
                private static void _Subject_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SendMail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>.Data> c, global::LightSwitchApplication.SendMail.DetailsClass d, object sf)
                {
                    c(d, ref d._Subject, sf);
                }
                private static bool _Subject_ComputeIsReadOnly(global::LightSwitchApplication.SendMail e)
                {
                    bool result = false;
                    e.Subject_IsReadOnly(ref result);
                    return result;
                }
                private static void _Subject_Validate(global::LightSwitchApplication.SendMail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Subject_Validate(r);
                }
                private static string _Subject_GetImplementationValue(global::LightSwitchApplication.SendMail.DetailsClass d)
                {
                    return d.ImplementationEntity.Subject;
                }
                private static void _Subject_SetImplementationValue(global::LightSwitchApplication.SendMail.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Subject = v;
                }
                private static void _Subject_OnValueChanged(global::LightSwitchApplication.SendMail e)
                {
                    e.Subject_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>.Entry
                    Body = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>.Entry(
                        "Body",
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Body_Stub,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Body_ComputeIsReadOnly,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Body_Validate,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Body_GetImplementationValue,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Body_SetImplementationValue,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Body_OnValueChanged);
                private static void _Body_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SendMail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>.Data> c, global::LightSwitchApplication.SendMail.DetailsClass d, object sf)
                {
                    c(d, ref d._Body, sf);
                }
                private static bool _Body_ComputeIsReadOnly(global::LightSwitchApplication.SendMail e)
                {
                    bool result = false;
                    e.Body_IsReadOnly(ref result);
                    return result;
                }
                private static void _Body_Validate(global::LightSwitchApplication.SendMail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Body_Validate(r);
                }
                private static string _Body_GetImplementationValue(global::LightSwitchApplication.SendMail.DetailsClass d)
                {
                    return d.ImplementationEntity.Body;
                }
                private static void _Body_SetImplementationValue(global::LightSwitchApplication.SendMail.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Body = v;
                }
                private static void _Body_OnValueChanged(global::LightSwitchApplication.SendMail e)
                {
                    e.Body_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>.Entry
                    Codigo = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>.Entry(
                        "Codigo",
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Codigo_Stub,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Codigo_ComputeIsReadOnly,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Codigo_Validate,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Codigo_GetImplementationValue,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Codigo_SetImplementationValue,
                        global::LightSwitchApplication.SendMail.DetailsClass.PropertySetProperties._Codigo_OnValueChanged);
                private static void _Codigo_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SendMail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>.Data> c, global::LightSwitchApplication.SendMail.DetailsClass d, object sf)
                {
                    c(d, ref d._Codigo, sf);
                }
                private static bool _Codigo_ComputeIsReadOnly(global::LightSwitchApplication.SendMail e)
                {
                    bool result = false;
                    e.Codigo_IsReadOnly(ref result);
                    return result;
                }
                private static void _Codigo_Validate(global::LightSwitchApplication.SendMail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Codigo_Validate(r);
                }
                private static string _Codigo_GetImplementationValue(global::LightSwitchApplication.SendMail.DetailsClass d)
                {
                    return d.ImplementationEntity.Codigo;
                }
                private static void _Codigo_SetImplementationValue(global::LightSwitchApplication.SendMail.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Codigo = v;
                }
                private static void _Codigo_OnValueChanged(global::LightSwitchApplication.SendMail e)
                {
                    e.Codigo_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, global::System.DateTime>.Data _Fecha;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>.Data _RolMail;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>.Data _MailTo;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>.Data _MailFrom;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>.Data _Subject;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>.Data _Body;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.SendMail, global::LightSwitchApplication.SendMail.DetailsClass, string>.Data _Codigo;
            
        }
    
        #endregion
    }
    
    #endregion
}
